#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

(cd web-frontend; npx lint-staged) &&
(cd web-backend; npx lint-staged) &&
(cd server; npx lint-staged) &&
(cd server-managed; npx lint-staged) &&
(cd sdk; npx lint-staged) &&
(cd cli; npx lint-staged) || exit
